config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  path: 'usuarios',
                      path_names: {
                        sign_in: 'entrar',
                        sign_out: 'sair',
                        password: 'senha',
                        new_user_password: '',
                        confirmation: 'confirmacao',
                        sign_up: 'cadastrar'
                      }

  get '/colaboradores/enviar-por-email', to: 'employees#send_by_mail', as: :employees_emailer
  resources :employees, path: 'colaboradores', path_names: { new: 'cadastrar', edit: 'editar' } do
    resources :contacts, path: 'contatos', path_names: { new: 'cadastrar', edit: 'editar' }
  end

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :employee
  belongs_to :contact_type

  validates :phone_number, format: {
              with: %r{\A\(\d{2}\)\d{4,5}-\d{4}\z},
              message: "Invalid phone. Use (41)3333-3333 or (41)33333-3333"
            }
end

app/models/contact_type.rb
class ContactType < ApplicationRecord
  has_many :contacts

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to  :sector
  has_many    :contacts

  validates :name, presence: true, uniqueness: true

  scope :partial_name, -> (name) { where('name like ?', "%#{name}%") }
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_many :employees

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery prepend: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_employee,  only: [:new, :create, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact          = Contact.new
    @contact.employee = @employee
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.employee = @employee

    if @contact.save
      redirect_to @employee, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    if @contact.update(contact_params)
      redirect_to @contact.employee, notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy

    redirect_to @employee, notice: 'Contact was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def set_employee
      @employee = Employee.find(params[:employee_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:employee_id, :contact_type_id, :phone_number)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee,  only: [:show, :edit, :update, :destroy]

  def index
    # Atribui à @search_filters o conteúdo dos parâmetros informados ou inicializa um hash vazio.
    @search_filters     = params[:filters] || {}
    employees           = Employee

    unless @search_filters.nil?
      employees = employees.partial_name(@search_filters[:name])          unless @search_filters[:name].blank?
      employees = employees.where(sector_id: @search_filters[:sector_id]) unless @search_filters[:sector_id].blank?
    end

    @employees = employees.includes(:sector).order(:name)
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee             = Employee.new
    @employee.name        = params[:employee][:name]
    @employee.birth_date  = params[:employee][:birth_date]
    @employee.sex         = params[:employee][:sex]
    @employee.sector_id   = params[:employee][:sector_id]

    if @employee.valid?
      @employee.save
      redirect_to employees_path, notice: 'Colaborador cadastrado com sucesso'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @employee             = Employee.find(params[:id])
    @employee.name        = params[:employee][:name]
    @employee.birth_date  = params[:employee][:birth_date]
    @employee.sex         = params[:employee][:sex]
    @employee.sector_id   = params[:employee][:sector_id]

    if @employee.valid?
      @employee.save
      redirect_to employees_path, notice: 'Colaborador atualizado com sucesso'
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy

    redirect_to employees_path, notice: 'Colaborador excluído com sucesso'
  end

  def send_by_mail
    EmployeeMailer.employees_email(current_user).deliver_now

    redirect_to employees_path, notice: 'Listagem enviada por email com sucesso'
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def ajusta_data(date)
    return if date.nil?

    date.strftime '%d/%m/%Y'
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_menu.html.erb
<div id="top_menu">
  <%= current_user.email %> |
  <%= link_to 'Sair', destroy_user_session_path, { method: :delete } %>
</div>

app/views/contacts/_form.html.erb
<%= form_for([employee, contact]) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :contact_type_id %>
    <%= f.collection_select :contact_type_id,
                            ContactType.order(name: :asc),
                            :id,
                            :name,
                            { include_blank: '- Selecione -' },
                            { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-success' %>
  <%= link_to 'Cancelar', employee_path(employee), class: 'btn btn-danger' %>
<% end %>

app/views/contacts/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Tipo de Contato</th>
      <th>Número</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% contacts.each do |contact| %>
      <tr>
        <td><%= contact.contact_type.name %></td>
        <td><%= contact.phone_number %></td>
        <td>
          <%= link_to edit_employee_contact_path(contact.employee, contact), class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to employee_contact_path(contact.employee, contact), method: :delete, data: { confirm: 'Está certo disto?' }, class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/edit.html.erb
<h1>Editar Contato</h1>

<%= render 'form', contact: @contact, employee: @contact.employee %>

app/views/contacts/new.html.erb
<h1>Cadastrar contato</h1>

<%= render 'form', contact: @contact, employee: @employee %>

app/views/employees/_filters.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Pesquisar</div>

  <div class="panel-body">
    <%= form_tag(employees_path, method: 'get') do %>
      <p>
        <%= label_tag :name, 'Nome' %>
        <%= text_field :filters, :name %>
      </p>

      <p>
        <%= label_tag :sector_id, 'Setor' %>
        <%= collection_select :filters, :sector_id,
                                 Sector.order(name: :asc),
                                :id,
                                :name,
                                {
                                    include_blank:  '- Selecione -',
                                   selected:    @search_filters[:sector_id]
                                 } %>
      </p>

      <%= submit_tag 'Pesquisar', class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation" style="background-color: #fcc">
      <h2><%= pluralize(@employee.errors.count, "erro") %> impede(m) salvar este colaborador</h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= f.label :birth_date %>
    <%= f.text_field :birth_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :sex %>
    <%= f.select :sex, [['Masculino', 'M'], ['Feminino', 'F']], {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :sector %>
    <%= f.collection_select :sector_id,
                            Sector.order(name: :asc),
                            :id,
                            :name,
                            { include_blank: '- Selecione -' },
                            { class: 'form-control' } %>
  </div>

  <%= f.submit 'Salvar', class: 'btn btn-success' %>
  <%= link_to 'Cancelar', employees_path, class: 'btn btn-danger' %>
<% end %>

app/views/employees/edit.html.erb
<h1>Alterar Colaborador</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<h1>Colaboradores</h1>

<%= render 'filters' %>

<%= link_to new_employee_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-plus"></span>
  Cadastrar Colaborador
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Setor</th>
      <th>Nascimento</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <%- @employees.each do |employee| %>
      <%- if employee.sex == 'M' %>
        <tr style="background-color: #CCF">
      <%- else -%>
        <tr style="background-color: #FCC">
      <%- end -%>
        <td><%= employee.id %></td>
        <td><%= employee.name %></td>
        <td><%= employee.sector.name %></td>
        <td><%= ajusta_data(employee.birth_date) %></td>
        <td>
          <%= link_to employee_path(employee), class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
          <%= link_to edit_employee_path(employee), class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to employee_path(employee), method: :delete, data: { confirm: 'Está certo disto?' }, class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <%- end %>
  </tbody>

  <tfoot>
  </tfoot>
</table>

<%= link_to 'Enviar por email', employees_emailer_path, class: 'btn btn-primary' %>

app/views/employees/new.html.erb
<h1>Cadastrar Colaborador</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<h1>Visualizar colaborador</h1>

<div class="form-group">
  <label>Nome</label>
  <div class="form-control-static"><%= @employee.name %></div>
</div>

<div class="form-group">
  <label>Sexo</label>
  <div class="form-control-static"><%= @employee.sex == 'M' ? 'Masculino' : 'Feminino' %></div>
</div>

<div class="form-group">
  <label>Data de Nascimento</label>
  <div class="form-control-static"><%= ajusta_data(@employee.birth_date) %></div>
</div>

<div class="form-group">
  <label>Setor</label>
  <div class="form-control-static"><%= @employee.sector.name %></div>
</div>

<fieldset>
  <legend>Contatos</legend>

  <%= render 'contacts/list', contacts: @employee.contacts %>
</fieldset>

<div class="btn-group" role="group">
  <%= link_to new_employee_contact_path(@employee), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Cadastrar Contato
  <% end %>

  <%= link_to employees_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Voltar
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursoRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'menu' %>
    <% end %>

    <% flash.each do |key, value| %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Login", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar-se", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu instruções de confirmação?", new_confirmation_path(resource_name) %><br />
<% end -%>

app/views/welcome/index.html.erb
<h1>Olá, Rails!</h1>